services:
  go1.15:
    image: golang:1.15-alpine3.13
    container_name: awstester-1.15
    environment:
      - GO111MODULE=on
      - AWS_PROFILE=localstack
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://192.168.100.201:4566
    volumes:
      - ./src:/go/src/myapps/awstester-v2
      - ./aws_credentials:/root/.aws
    working_dir: /go/src/myapps/awstester-v2
    entrypoint: ["ash"]
    stdin_open: true 
    tty: true 
    restart: unless-stopped
  
  go1.16:
    image: golang:1.16-alpine3.13
    container_name: awstester-1.16-alpine
    environment:
      - GO111MODULE=on
      - AWS_PROFILE=localstack
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://192.168.100.201:4566
    volumes:
      - ./src:/go/src/myapps/awstester-v2
      - ./aws_credentials:/root/.aws
    working_dir: /go/src/myapps/awstester-v2
    entrypoint: ["ash"]
    stdin_open: true 
    tty: true 
    restart: unless-stopped
  
  go1.17:
    image: golang:1.17-alpine3.13
    container_name: awstester-1.17
    environment:
      - GO111MODULE=on
      - AWS_PROFILE=localstack
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://192.168.100.201:4566
    volumes:
      - ./src:/go/src/myapps/awstester-v2
      - ./aws_credentials:/root/.aws
    working_dir: /go/src/myapps/awstester-v2
    entrypoint: ["ash"]
    stdin_open: true 
    tty: true 
    restart: unless-stopped
